import Link from "next/link";

const LINKS = [
  { label: "Create a story", href: "/generate" },
  { label: "Story library", href: "/stories" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "FAQ", href: "/#faq" },
];

export function Footer() {
  return (
    <footer className="border-t border-white/10 bg-[var(--surface)]">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col items-center gap-6 sm:flex-row sm:items-start sm:justify-between">
          <div className="text-center sm:text-left">
            <p className="font-display text-lg text-gradient-magic">✨ StoryBook AI</p>
            <p className="mt-1 max-w-xs text-sm text-[var(--muted)]">
              AI-illustrated bedtime stories, made in seconds. Free to create, fun to share.
            </p>
          </div>
          <nav className="font-data flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs tracking-wide text-[var(--muted)] uppercase sm:justify-end">
            {LINKS.map((l) => (
              <Link key={l.href} href={l.href} className="transition hover:text-[var(--gold)]">
                {l.label}
              </Link>
            ))}
          </nav>
        </div>
        <p className="font-data mt-10 text-center text-xs tracking-wide text-[var(--muted)]/70">
          © {new Date().getFullYear()} STORYBOOK_AI — ALL STORIES GENERATED BY AI FOR ENTERTAINMENT PURPOSES
        </p>
      </div>
    </footer>
  );
}
