import Link from "next/link";
import { listStories } from "@/lib/api";
import { StoryCard } from "@/components/StoryCard";
import { THEME_OPTIONS } from "@/lib/types";

export default async function StoriesPage({ searchParams }: PageProps<"/stories">) {
  const { theme } = await searchParams;
  const activeTheme = typeof theme === "string" ? theme : undefined;

  const stories = await listStories({ isDefault: true, theme: activeTheme, limit: 48 }).catch(() => []);

  return (
    <div className="bg-void-texture min-h-screen">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <h1 className="font-display text-3xl font-bold text-white">Story Library</h1>
        <p className="mt-2 text-[var(--muted)]">Stories generated by the community and our team.</p>

        <div className="mt-6 flex flex-wrap gap-2">
          <Link
            href="/stories"
            className={`rounded-full px-4 py-1.5 text-sm font-semibold transition ${
              !activeTheme
                ? "bg-gradient-to-r from-[var(--coral)] to-[var(--gold)] text-[#1A1330]"
                : "border border-white/10 bg-[var(--surface)] text-white"
            }`}
          >
            All themes
          </Link>
          {THEME_OPTIONS.map((t) => {
            const isActive = activeTheme?.toLowerCase() === t.name.toLowerCase();
            return (
              <Link
                key={t.name}
                href={`/stories?theme=${encodeURIComponent(t.name)}`}
                className="rounded-full border px-4 py-1.5 text-sm font-semibold transition"
                style={
                  isActive
                    ? { backgroundColor: t.color, borderColor: t.color, color: "white" }
                    : { backgroundColor: `${t.color}18`, borderColor: `${t.color}40`, color: t.color }
                }
              >
                {t.name}
              </Link>
            );
          })}
        </div>

        {stories.length === 0 ? (
          <div className="mt-10 rounded-2xl border border-dashed border-white/10 bg-white/5 p-12 text-center backdrop-blur-lg">
            <p className="text-[var(--muted)]">
              {activeTheme ? `No ${activeTheme} stories yet — be the first!` : "No stories yet — be the first!"}
            </p>
            <Link
              href="/generate"
              className="mt-4 inline-block rounded-full bg-gradient-to-r from-[var(--coral)] to-[var(--gold)] px-6 py-2 font-semibold text-[#1A1330] shadow-[0_0_20px_-5px_rgba(255,200,87,0.4)]"
            >
              Create a story
            </Link>
          </div>
        ) : (
          <div className="mt-8 columns-1 gap-6 sm:columns-2 lg:columns-4 [&>*]:mb-6 [&>*]:break-inside-avoid">
            {stories.map((story) => (
              <StoryCard key={story.id} story={story} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
