import Link from "next/link";
import Image from "next/image";
import { listStories } from "@/lib/api";
import { THEME_OPTIONS } from "@/lib/types";
import { HERO_IMAGE_URL } from "@/lib/constants";
import { ThemeCard } from "@/components/ThemeCard";
import { StoryCard } from "@/components/StoryCard";
import { HeroGenerator } from "@/components/HeroGenerator";
import { TrustBadges } from "@/components/TrustBadges";
import { AudioDemo } from "@/components/AudioDemo";
import { FeaturesSection } from "@/components/FeaturesSection";
import { SampleSpread } from "@/components/SampleSpread";
import { WhyChooseSection } from "@/components/WhyChooseSection";
import { ComparisonSection } from "@/components/ComparisonSection";
import { FAQSection } from "@/components/FAQSection";
import { FinalCTA } from "@/components/FinalCTA";

const STEPS = [
  { step: "1", title: "Describe your story", body: "Choose a theme and tell us who's in the story and what happens." },
  { step: "2", title: "AI writes & illustrates", body: "Gemini writes a 10-page story and paints a picture for every page." },
  { step: "3", title: "Read, listen & share", body: "Flip through the pages, hear it narrated aloud, download a PDF, or share the link." },
];

export default async function HomePage() {
  const [featured, recent] = await Promise.all([
    listStories({ isDefault: true, limit: 8 }).catch(() => []),
    listStories({ limit: 12 }).catch(() => []),
  ]);
  const library = featured.length > 0 ? featured : recent;
  const spreadStory = recent.find((s) => s.pages.some((p) => p.imageUrl)) ?? null;

  return (
    <div>
      <section className="bg-void-texture relative flex min-h-screen flex-col justify-center overflow-hidden px-6 py-24">
        <div className="pointer-events-none absolute -top-24 -right-24 h-96 w-96 rounded-full bg-[var(--gold)] opacity-10 blur-[120px]" />
        <div className="pointer-events-none absolute -bottom-24 -left-24 h-96 w-96 rounded-full bg-[var(--violet)] opacity-10 blur-[120px]" />

        <div className="relative mx-auto grid w-full max-w-6xl grid-cols-1 items-center gap-14 lg:grid-cols-2">
          <div className="text-center lg:text-left">
            <p className="font-data inline-block rounded-full border border-[var(--gold)]/30 bg-[var(--gold)]/10 px-4 py-1 text-xs font-medium tracking-widest text-[var(--gold)] uppercase">
              ✨ Free AI storybook generator
            </p>
            <h1 className="font-display mt-6 text-4xl leading-tight font-bold text-white sm:text-5xl lg:text-6xl">
              Turn any idea into a <span className="text-gradient-magic">magical bedtime story</span>
            </h1>
            <p className="mx-auto mt-5 max-w-xl text-lg text-[var(--muted)] lg:mx-0">
              Write a prompt and StoryBook AI writes and illustrates a full 10-page storybook — narrated,
              shareable, and yours to keep.
            </p>

            <div className="mt-6 inline-flex items-center gap-2 rounded-full bg-[var(--success)]/10 px-4 py-2 text-sm font-semibold text-[var(--success)]">
              ✅ 100% free — sign up in seconds to start creating
            </div>

            <div className="mt-8 flex flex-col justify-center gap-4 sm:flex-row lg:justify-start">
              <Link
                href="/generate"
                className="rounded-full bg-gradient-to-r from-[var(--coral)] to-[var(--gold)] px-8 py-3.5 font-display font-semibold text-[#1A1330] shadow-[0_0_20px_-5px_rgba(255,200,87,0.5)] transition-all duration-300 hover:scale-105 hover:shadow-[0_0_30px_-5px_rgba(255,200,87,0.6)]"
              >
                ✨ Create your story
              </Link>
              <Link
                href="/stories"
                className="rounded-full border border-white/15 px-8 py-3.5 font-display font-semibold text-white transition hover:border-[var(--gold)]/40"
              >
                Browse story library
              </Link>
            </div>
          </div>

          {/* Cartoon-kid hero illustration, generated by the app's own AI pipeline */}
          <div className="relative mx-auto aspect-square w-full max-w-md lg:max-w-lg">
            <div className="absolute inset-0 animate-[spin_18s_linear_infinite] rounded-full border border-dashed border-[var(--gold)]/25" />
            <div className="absolute inset-6 animate-[spin_24s_linear_infinite] rounded-full border border-dashed border-[var(--violet)]/25 [animation-direction:reverse]" />
            <div className="animate-float absolute inset-10 overflow-hidden rounded-[2.5rem] border-2 border-white/10 shadow-[0_0_60px_-10px_rgba(255,200,87,0.35)]">
              <Image
                src={HERO_IMAGE_URL}
                alt="A cartoon child reading a glowing magical storybook, illustrated by StoryBook AI"
                fill
                priority
                unoptimized
                className="object-cover"
              />
            </div>
          </div>
        </div>

        <div className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 flex-col items-center gap-1 text-[var(--muted)] sm:flex">
          <span className="font-data text-[10px] tracking-widest uppercase">Try it now</span>
          <span className="animate-bounce text-lg">↓</span>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="font-display text-center text-2xl font-bold text-white">Write your story below</h2>
        <p className="mx-auto mt-2 max-w-md text-center text-[var(--muted)]">Pick a theme, describe your idea, and watch it come to life.</p>
        <div className="mt-8">
          <HeroGenerator />
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-16">
        <TrustBadges />
      </section>

      <section className="mx-auto max-w-6xl px-6 py-8">
        <h2 className="font-display text-center text-2xl font-bold text-white">Pick a world to explore</h2>
        <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
          {THEME_OPTIONS.map((t) => (
            <ThemeCard key={t.name} {...t} />
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-16">
        <AudioDemo />
      </section>

      {library.length > 0 && (
        <section className="mx-auto max-w-6xl px-6 py-16">
          <div className="flex items-center justify-between">
            <h2 className="font-display text-2xl font-bold text-white">
              {featured.length > 0 ? "Featured stories" : "Fresh from the library"}
            </h2>
            <Link href="/stories" className="font-data text-xs tracking-wide text-[var(--gold)] uppercase">
              View all →
            </Link>
          </div>
          <div className="mt-8 columns-2 gap-6 sm:columns-3 lg:columns-4 [&>*]:mb-6 [&>*]:break-inside-avoid">
            {library.map((story) => (
              <StoryCard key={story.id} story={story} />
            ))}
          </div>
        </section>
      )}

      <FeaturesSection />

      <SampleSpread story={spreadStory} />

      <WhyChooseSection />

      <ComparisonSection />

      <section id="how-it-works" className="mx-auto max-w-6xl px-6 py-16">
        <h2 className="font-display text-center text-2xl font-bold text-white">How it works</h2>

        <div className="relative mt-14 grid grid-cols-1 gap-8 sm:grid-cols-3">
          {/* connecting gradient line, desktop only */}
          <div className="absolute top-6 right-[16%] left-[16%] hidden h-px bg-gradient-to-r from-[var(--coral)] via-[var(--gold)] to-[var(--violet)] opacity-40 sm:block" />

          {STEPS.map((item) => (
            <div key={item.step} className="relative">
              <div className="relative z-10 mx-auto -mb-6 flex h-12 w-12 items-center justify-center rounded-full bg-gradient-to-br from-[var(--coral)] to-[var(--gold)] font-display font-bold text-[#1A1330] shadow-[0_0_20px_-5px_rgba(255,200,87,0.6)]">
                {item.step}
              </div>
              <div
                className="group relative border border-white/10 bg-[var(--surface)] p-6 pt-10 text-center transition-all duration-300 hover:border-[var(--gold)]/40 hover:shadow-[0_0_30px_-10px_rgba(255,200,87,0.25)]"
                style={{ clipPath: "polygon(0 0, calc(100% - 28px) 0, 100% 28px, 100% 100%, 0 100%)" }}
              >
                <div className="absolute top-0 left-0 h-4 w-4 rounded-tl-lg border-t-2 border-l-2 border-[var(--gold)] opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                <div className="absolute right-0 bottom-0 h-4 w-4 rounded-br-lg border-r-2 border-b-2 border-[var(--violet)] opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                <p className="font-display font-bold text-white">{item.title}</p>
                <p className="mt-2 text-sm text-[var(--muted)]">{item.body}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <div id="faq">
        <FAQSection />
      </div>

      <FinalCTA />
    </div>
  );
}
